---
- hosts: "localhost"
  tasks:
    - name: Get Instance Facts
      ec2_instance_info:
        instance_ids:
          - "{{ instance_id }}"
      register: orig_instance_state

    - name: Stop EC2
      ec2_instance:
        instance_ids:
          - "{{ instance_id }}"
        state: stopped
        wait: true
        wait_timeout: 600
        instance_initiated_shutdown_behavior: stop

    - name: Start EC2
      ec2_instance:
        instance_ids:
          - "{{ instance_id }}"
        state: running
        wait: true
        wait_timeout: 600

    - name: Get Instance Facts
      ec2_instance_info:
        instance_ids:
          - "{{ instance_id }}"
      register: instance_state

    - name: Test Stop-Start
      assert:
        that:
          - " orig_instance_state.instances[0].launch_time != instance_state.instances[0].launch_time "

